### ISSUE TITLE
webrtc v1.0.0-alpha2 zeroing all subsequent binary data of the packet after one null byte send

### ISSUE THREAD

**Issue by XDRiVE888** [godotengine/webrtc-native#55]
### Godot version

v3.4.4.stable.official [419e713a2]

### Plugin version

v1.0.0-alpha2

### System information

Windows 10

### Issue description
Zeroing all subsequent binary data of the packet after one null byte sending.
Datachannel connection successfull, but when you try to send binary data via datachannel for example put_packet(PoolByteArray([1,2,0,4,5,6,7,8,9]) at another side you recieved [1,2,0,0,0,0,0,0,0]

### Steps to reproduce

try to send put_packet(PoolByteArray([1,2,0,4,5,6,7,8,9]) via data channel and recieve result at other side.

### Minimal reproduction project

[WebRTC Minimal Demo.zip](https://github.com/godotengine/webrtc-native/files/8934420/WebRTC.Minimal.Demo.zip)
need to add webrtc native v1.0.0-alpha2 to this demo godot progect, i removed them becaurse file size too big for upload.

**Comment by Faless** [comment]
First of all, thanks for helping test the new version.

I believe this is due to the changed default write mode.

Default write mode is now "WRITE_MODE_TEXT" so sending non text data will
fail.

Can you try setting:
`channel.write_mode = WRITE_MODE_BINARY` before sending data? That should
fix the issue.

In hindsight I think we should revert the default to `WRITE_MODE_BINARY` to
avoid this kind of confusion.

**Comment by XDRiVE888** [comment]
> channel.write_mode = WRITE_MODE_BINARY
Indeed, with the option channel.write_mode = WRITE_MODE_BINARY everything works fine. Thanks for the tip. I was happy to test, and also want to thank you very much for your work.
