### ISSUE TITLE
The macos library only supports x86 architectures

### ISSUE THREAD

**Issue by BimDav** [godotengine/webrtc-native#58]
### Godot version

3.4.4-stable

### Plugin version

0.5

### System information

MacOS, M2

### Issue description

When loading the library on a M2 Mac:

E 0:00:00.186   open_dynamic_library: Can't open dynamic library: /Users/BimDav/Developer/AGoodDay/webrtc/lib/libwebrtc_native.osx.release.64.dylib, error: dlopen(/Users/BimDav/Developer/AGoodDay/webrtc/lib/libwebrtc_native.osx.release.64.dylib, 0x0002): tried: '/Users/BimDav/Developer/AGoodDay/webrtc/lib/libwebrtc_native.osx.release.64.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')).
  <Erreur C++>  Condition "!p_library_handle" is true. Returned: ERR_CANT_OPEN
  <Source C++>  platform/osx/os_osx.mm:1917 @ open_dynamic_library()

### Steps to reproduce

Use the official release library on a mac with arm architecture

**Comment by Faless** [comment]
MacOS `arm64` builds are now supported in the [new `master` releases](https://github.com/godotengine/webrtc-native/releases/) which use libdatachannel as a WebRTC library (e.g. [1.0.0-beta5](https://github.com/godotengine/webrtc-native/releases/tag/1.0.0-beta5)) which also have a Godot 3.x version.

There is no plan to further support the old versions which use the chromium WebRTC library since that library is unmaintainable.

Closing as fixed in new releases.
